feat(gitopscli/*): add merge method parameter to deploy command
baloise/gitopscli pull request #155
Opened 2021-06-29 09:11 UTC by socar-humphrey

Hi, 

In my usecase, I needed to select a merge method other than `Create a Merge Commit`, but there's no merge method selection option on deploy command by default.

I added a merge method parameter to deploy command, so that it enables users to pick one of `squash`, `rebase`, `merge commit`(if it is set to None)

2021-06-29 12:28 UTC, joachimprinzbach reviewed
Would be great to have the docs updated as well: https://github.com/baloise/gitopscli/blob/master/docs/commands/deploy.md

2021-06-29 12:28 UTC, joachimprinzbach commented on gitopscli/cliparser.py
> +    parser.add_argument("--merge-method", help="Merge Method (squash, rebase, merge commit if None)", type=str,
Maybe use "merge-commit" as default instead of none. Syntactically, "none" would not be a valid method

2021-06-30 11:21 UTC, christiansiegel requested changes
I don't know why travis is not building 🤔 

There are some broken tests, formatting, etc. I added a Readme section on how to run those in #156

2021-06-30 11:21 UTC, christiansiegel commented on gitopscli/cliparser.py
> +                        default="merge")
If you default to `merge` then defining `merge_method` as `Optional[..]` makes no sense.

However, I would remove the default value from the cli. Hence, if the `--merge-method` is not specified, the Git server can use its default merge method -> no breaking change for existing users.

2021-06-30 11:21 UTC, christiansiegel commented on gitopscli/git_api/github_git_repo_api_adapter.py
> +    def merge_pull_request(self, pr_id: int, merge_method: Optional[Literal["squash", "rebase", "merge"]] = "merge") -> None:
You did not implement the `merge_method` parameter for the Bitbucket and GitLab implementations.

2021-07-01 00:59 UTC, socar-humphrey commented
A little tip for better DX: add [pre-commit](https://travis-ci.com/github/baloise/gitopscli/jobs/520716793) for formatting and tests.
https://travis-ci.com/github/baloise/gitopscli/jobs/520716793

This build has failed bc of a little formatting issue. Pre-commit enables codes not only to be in the project-wide format setting in commit level, but also to be passing tests before making a commit. It did boost my team's development cycle IMO.

2021-07-01 19:49 UTC, christiansiegel commented
> A little tip for better DX: add [pre-commit](https://travis-ci.com/github/baloise/gitopscli/jobs/520716793) for formatting and tests.
> https://travis-ci.com/github/baloise/gitopscli/jobs/520716793

Good idea! Added in #158

2021-07-02 10:21 UTC, socar-humphrey commented
@christiansiegel @joachimprinzbach 
Plz lmk if I need to add anything else for this PR. (I think its ready for merge)

2021-07-02 20:58 UTC, joachimprinzbach commented
lgtm - @christiansiegel could you approve pls?

2021-07-04 12:00 UTC, christiansiegel approved these changes
I'm still missing any doc or log message for Bitbucket and Gitlab if the chosen merge method is not supported and just ignored. But we can add that later..

Thanks for the feature @socar-humphrey!

2021-07-04 12:00 UTC, merged

2021-07-04 12:07 UTC, christiansiegel commented
:tada: This PR is included in version 4.7.0 :tada:

The release is available on:
- `v4.7.0`
- [GitHub release](https://github.com/baloise/gitopscli/releases/tag/v4.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: