feat: use customizable message templates for PR comments
baloise/gitopscli pull request #175
Opened 2022-03-30 16:01 UTC by koenigle

Allows one to define custom message templates in the .gitops.config.yml which are used for the PR comments
If no templates are specified, default messages are used

Example .gitops.config.yml
```apiVersion: v2
applicationName: my-application
messages:
  created: "Created preview for ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
  updated: "Updated preview to ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
  uptodate: "Your application is already up to date with ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
```

2022-03-30 16:37 UTC, christiansiegel commented
Thanks, great idea :+1: 
Could you please also update the docs? (https://github.com/baloise/gitopscli/blob/master/docs/includes/preview-configuration.md)

2022-03-30 16:38 UTC, christiansiegel requested changes
Thanks, great idea :+1: 
Could you please also update the docs? (https://github.com/baloise/gitopscli/blob/master/docs/includes/preview-configuration.md)

2022-03-30 16:38 UTC, christiansiegel commented on gitopscli/gitops_config.py
> +                "messages.created",
Maybe `previewConfig.messages.created` would be a better place in the yaml structure? https://baloise.github.io/gitopscli/commands/create-pr-preview/#gitopsconfigyaml

2022-03-30 18:41 UTC, christiansiegel commented
(BTW: I see you're working @baloise. You can become part of github organization by adding your handle to the [org](https://github.com/baloise/org) repo :wink: Example: https://github.com/baloise/org/pull/43)

2022-03-30 19:55 UTC, koenigle commented on gitopscli/gitops_config.py
> +                "messages.created",
For me the `previewConfig.*` path looked more like technical configuration of the preview environment whereas the messages are rather general information for the GitOps Bot, thus I thought a different path would be suitable
However I do not have a strong opinion on this, we can also move to `previewConfig` if this suits better

2022-03-31 05:37 UTC, christiansiegel commented
FYI: The build currently fails due to a general issue. Will be fixed with #176

2022-03-31 05:44 UTC, christiansiegel commented on gitopscli/gitops_config.py
> +                "messages.created",
If it's in a general section it should at least have a more specific name like `messages.prPreviewCreated`.
@niiku Any opinion on this?

2022-03-31 09:27 UTC, joachimprinzbach commented on gitopscli/gitops_config.py
> +                "messages.created",
For me, the general section would make sene - as it is not related to a specific preview. Even though the message content at the end is. 

I like the approach from @christiansiegel with a structure for messages and descriptive props, example:
- messages.previewEnvUpdated
- messages.previewEnvAlreadyUpToDate
- messages.previewEnvCreated

2022-04-01 15:31 UTC, koenigle commented on gitopscli/gitops_config.py
> +                "messages.created",
I updated documentation and configuration path according to your suggestions.

2022-04-01 16:01 UTC, christiansiegel approved these changes
looks good to me :heavy_check_mark:

2022-04-07 06:44 UTC, niiku approved these changes
lgtm. Thank you very much for your contribution!

2022-04-07 07:36 UTC, merged

2022-04-07 07:44 UTC, baopso commented
:tada: This PR is included in version 5.2.0 :tada:

The release is available on:
- `v5.2.0`
- [GitHub release](https://github.com/baloise/gitopscli/releases/tag/v5.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: