Print hashes of every commit when deploying
baloise/gitopscli pull request #185
Opened 2022-10-07 13:17 UTC by robert-groensfeld

I altered the deploy command so that hashes of all commits are printed and we can use them for postprocessing in our pipeline. I had to update black and reformat a couple of files because of a [compatibility issue](https://github.com/psf/black/issues/2964). Unfortunately I couldn't think of a good way to test the case when there is no output by the deploy command (when no commits are made). Maybe someone of you has an idea how to cleanly mock the nested call to commit. Also I am not too happy with parsing the short hashes from the command line output but this is the return value I get from the commit method.

2022-10-07 14:33 UTC, christiansiegel commented
I believe there are a few commits to much on your branch 🤔

2022-10-07 14:45 UTC, christiansiegel requested changes
_(see previous comment)_

2022-10-07 15:45 UTC, robert-groensfeld commented
After some pretty ugly cherry picks I managed only to keep those 4 files. Sorry for the inconvenience.

2022-10-08 18:21 UTC, christiansiegel commented on gitopscli/git_api/git_repo.py
> +                return self.__get_hash(output)
I think
```python
return self.__get_repo().head.commit.hexsha
```
would also do the trick

2022-10-08 18:21 UTC, christiansiegel commented on gitopscli/commands/deploy.py
> +            print(commit_hash)
Why not just logging it in `git_repo.py`? Similar to `logging.info("Creating commit with message: %s", message)` => `logging.info("Created commit with hash: %s", hexsha)`.

2022-10-08 18:58 UTC, christiansiegel commented
btw: the build failed due to a broken dependency. Fix is on master now: 5f3a443e7ecb3723c1a71b9744e2993c0b6dfc00

2022-10-10 13:33 UTC, robert-groensfeld commented on gitopscli/commands/deploy.py
> +            print(commit_hash)
I also thought about this, then decided against it because of the following reasons:

- The log level of the application decides if logs are printed. Changes in the log level will break our client app. This may not be obvious to the person changing it.
- Log messages may be written to some other place than stdout in the future. In this case our client app will not work and it won't be obvious to the person changing it.
- Printing to stdout is the default behavior of the most command line interfaces. Output can be piped to other programs if necessary.

Do you still want me to do it?

2022-10-10 13:48 UTC, robert-groensfeld commented on gitopscli/git_api/git_repo.py
> +                return self.__get_hash(output)
What if the commit fails for some reason (e.g. no files selected to commit)? Won't HEAD point to the last commit and make the output invalid?

2022-10-10 16:00 UTC, christiansiegel commented on gitopscli/commands/deploy.py
> +            print(commit_hash)
Fair arguments. However, I don't really like the idea of "randomly" printing values. What happens if we want to print something additional in the future? Maybe we could collect everything of interest and print something structured in the end? Json?

2022-10-12 15:51 UTC, robert-groensfeld commented on gitopscli/commands/deploy.py
> +            print(commit_hash)
Yes you are right. I didn't want to over-engineer it on the first iteration. Let's introduce a `--json` command line parameter which creates a deployment object and pretty-prints it on stdout if the deployment was successful.

2022-10-14 16:05 UTC, merged

2022-10-14 16:11 UTC, baopso commented
:tada: This PR is included in version 5.4.0 :tada:

The release is available on:
- `v5.4.0`
- [GitHub release](https://github.com/baloise/gitopscli/releases/tag/v5.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: