chore(Upgrade to python 3.10 with compatibility fixes)
baloise/gitopscli pull request #189
Opened 2022-10-20 15:56 UTC by makrelas

Update image python to version 3.10.
changes:
- by default argparse prints options: instead of optional arguments:
- typed-ast prerequisite for mypy 0.790 in version 1.4.3 had problem with new python version, upgraded both to latest
- mypy upgrade required exclusion of some paths
- linter recommendation applied - remove f-strings where unused,

2022-10-20 16:20 UTC, niiku requested changes

2022-10-20 16:20 UTC, niiku commented on .pylintrc
> +        duplicate-code
Maybe add a comment why duplicate checks are disable

2022-10-20 16:20 UTC, niiku commented on requirements-test.txt
> +black==22.10.0
what about updating non-test dependencies?

2022-10-20 16:22 UTC, makrelas commented on requirements-test.txt
> +black==22.10.0
black is linting/formatting tool as well, I can keep it in the same version as it was before - although update did not seem to change test behaviour

2022-10-20 16:36 UTC, makrelas commented on .pylintrc
> +        duplicate-code
Some of the stuff does look like it could use a rewrite later on (Bitbucket and Gitlab adapter are quite similar), but most rather is either a false positive (similar imports in different files for example),, or something that after removal may cause code to be less readable.

************ Module gitopscli.commands.create_preview
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 2 files
==gitopscli.git_api.bitbucket_git_repo_api_adapter:53
==gitopscli.git_api.gitlab_git_repo_api_adapter:47
    def create_pull_request_to_default_branch(
        self, from_branch: str, title: str, description: str
    ) -> GitRepoApi.PullRequestIdAndUrl:
        to_branch = self.__get_default_branch()
        return self.create_pull_request(from_branch, to_branch, title, description)

    def create_pull_request(
        self, from_branch: str, to_branch: str, title: str, description: str
    ) -> GitRepoApi.PullRequestIdAndUrl: (duplicate-code)
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 2 files
==gitopscli.git_api.bitbucket_git_repo_api_adapter:10
==gitopscli.git_api.gitlab_git_repo_api_adapter:14
    def __init__(
        self,
        git_provider_url: str,
        username: Optional[str],
        password: Optional[str],
        organisation: str,
        repository_name: str,
    ) -> None: (duplicate-code)
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 2 files
==gitopscli.commands.__init__:3
==gitopscli.commands.command_factory:2
from .add_pr_comment import AddPrCommentCommand
from .create_preview import CreatePreviewCommand
from .create_pr_preview import CreatePrPreviewCommand
from .delete_preview import DeletePreviewCommand
from .delete_pr_preview import DeletePrPreviewCommand
from .deploy import DeployCommand
from .sync_apps import SyncAppsCommand
from .version import VersionCommand (duplicate-code)
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 2 files
==gitopscli.commands.create_pr_preview:35
==gitopscli.commands.delete_pr_preview:25
                username=args.username,
                password=args.password,
                git_user=args.git_user,
                git_email=args.git_email,
                organisation=args.organisation,
                repository_name=args.repository_name,
                git_provider=args.git_provider,
                git_provider_url=args.git_provider_url, (duplicate-code)
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 6 files
==gitopscli.commands.create_pr_preview:8
==gitopscli.commands.create_preview:14
==gitopscli.commands.delete_pr_preview:7
==gitopscli.commands.delete_preview:12
==gitopscli.commands.deploy:11
==gitopscli.commands.sync_apps:11
    @dataclass(frozen=True)
    class Args(GitApiConfig):
        git_user: str
        git_email: str

        organisation: str
        repository_name: str
 (duplicate-code)
gitopscli/commands/create_preview.py:1:0: R0801: Similar lines in 2 files
==gitopscli.commands.add_pr_comment:16
==gitopscli.commands.create_pr_preview:19
    def __init__(self, args: Args) -> None:
        self.__args = args

    def execute(self) -> None:
        args = self.__args
        git_repo_api = GitRepoApiFactory.create(args, args.organisation, args.repository_name) (duplicate-code)

2022-10-20 17:41 UTC, christiansiegel commented
Thanks for upgrading! Two missing details:
- `.gitpod.yml` uses the default workspace image which comes with python 3.8. Please define a specific workspace image for python 3.10 (doc: https://www.gitpod.io/docs/configure/workspaces/workspace-image)
- `README.md` still contains a python 3.8 badge: https://github.com/baloise/gitopscli/blob/master/README.md?plain=1#L4

We're also using [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/#summary) to automatically generate a changelog and increase the gitopscli version. Please make sure your commit messages adhere to it :wink:

2022-10-20 23:27 UTC, makrelas commented
Applied changes as requested.

2022-10-21 04:37 UTC, christiansiegel approved these changes

2022-10-21 11:30 UTC, niiku approved these changes

2022-10-21 11:31 UTC, merged