refactor: change of a sync_apps.py logic
baloise/gitopscli pull request #190
Opened 2022-10-21 14:19 UTC by makrelas

Moved Root repository and Application Tenant configurations to be treated as object, including additional option of tenant repository traversal to obtain custom configurations.

The idea behind it is to use this 2 classes in new commands (querying of the config of repo/listing tenant apps, getting user customizations etc.)

RootRepo and AppTennantConfig currently are explicitly defined in sync_apps.py (importing it externally requires even more of a tests rewrite), some of the linter tests are disabled as well - as this is a POC to gather feedback about the direction I'm going.

2022-11-17 17:13 UTC, niiku requested changes

2022-12-08 22:21 UTC, makrelas commented on gitopscli/commands/sync_apps.py
> +            current_repo_apps[app].insert(0, "customAppConfig", custom_app_config_item)
Solution without insert does work as well.

2022-12-08 22:24 UTC, makrelas commented on gitopscli/commands/sync_apps.py
> +        if current_repo_apps.get(app) is not None:
If app properties will be empty - it will return None as well - and rest will not work.

2022-12-24 15:17 UTC, niiku approved these changes

2022-12-24 15:19 UTC, merged