added pr labels for gitlab and github, and merge parameters for gitlab
baloise/gitopscli pull request #194
Opened 2023-01-20 19:15 UTC by epanoff

2023-01-28 08:12 UTC, christiansiegel requested changes
Thanks for the PR and sorry for the late review - a bit busy at the moment.

Please don't forget to also update the docs: https://github.com/baloise/gitopscli/blob/master/docs/commands/deploy.md

What is the issue with testing on Github?

2023-01-28 08:12 UTC, christiansiegel commented on gitopscli/git_api/bitbucket_git_repo_api_adapter.py
> +        gitlab_merge_parameters: Dict[str, Any],
The more I look at it: Having "gitlab" in the interface just doesn't feel right. We should name that simply `merge_parameters`/`--merge-parameters`. Who knows, maybe this generic object will be useful for another adapter in the future...

2023-01-28 08:12 UTC, christiansiegel commented on gitopscli/cliparser.py
> +def __check_compatibility_args(args: Dict[str, Any], error: Callable[[str], NoReturn]) -> None:
Maybe move that check into the individual adapters. That's where we know for sure if someting is supported or not.

2023-01-28 08:12 UTC, christiansiegel commented on gitopscli/git_api/gitlab_git_repo_api_adapter.py
> +    def merge_pull_request_with_parameters(
please don't duplicate code :wink:

2023-03-24 13:20 UTC, epanoff commented on gitopscli/cliparser.py
> +        "--pr-labels", help="JSON object pr labels (Gitlab, Github supported)", type=__parse_yaml, default=None
Renamed

2023-03-24 13:20 UTC, epanoff commented on gitopscli/commands/deploy.py
> +        gitlab_merge_parameters: Any
Done

2023-03-24 13:21 UTC, epanoff commented on gitopscli/cliparser.py
> +def __check_compatibility_args(args: Dict[str, Any], error: Callable[[str], NoReturn]) -> None:
Just deleted this check. If not supporting - do nothing

2023-03-24 13:21 UTC, epanoff commented on gitopscli/git_api/gitlab_git_repo_api_adapter.py
> +    def merge_pull_request_with_parameters(
ok

2023-04-06 11:36 UTC, christiansiegel commented
@epanoff is this ready for review? PR is still in draft mode :wink:

2023-04-06 13:21 UTC, epanoff commented
Sorry. I've changed mode.

2023-04-07 15:44 UTC, christiansiegel approved these changes
lgtm. Thanks!

Can you please merge the latest master into you PR branch? We changed to Github actions in the meantime. Just so the tests run before merging the PR :wink:

2023-04-09 12:31 UTC, christiansiegel commented
Nevermind, ran the tests locally :robot:

2023-04-09 12:33 UTC, merged